// src/lib/photos.ts
export type Photo = { src: string; alt?: string; info?: string };

export const PHOTOS: Photo[] = [
  { src: "/photos/IP2A0094.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0197.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0097.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0218.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0099.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0222.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0101.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0102.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0104.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0105.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0106.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0107.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0096.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0201.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0214.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0216.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0098.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0100.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0224.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0227.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0229.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0233.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0234.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0235.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0237.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0238.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0243.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0244.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0248.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0250.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0251.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0259.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0266.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0271.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0272.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0274.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0276.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0278.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0280.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0297.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0301.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0303.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0304.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0306.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0307.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0314.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0315.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0316.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0318.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0319.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0321.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0322.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0324.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0327.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0330.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0331.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0336.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0338.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0339.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0343.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0344.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0345.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0352.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0353.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0356.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0357.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0361.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0366.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0373.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0374.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0381.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0384.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0387.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0389.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0395.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0399.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0404.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0407.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0413.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0416.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0417.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0420.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0422.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0426.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0428.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0432.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0436.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0437.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0440.jpg", alt: "Säynätsalon kunntalo", info: "Finlande - Alvar Aalto" }, 
  { src: "/photos/IP2A0443.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0447.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0454.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0456.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0457.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0459.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0460.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0461.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0462.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0464.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0466.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0467.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0470.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0472.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0474.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0475.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0476.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0477.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0478.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0479.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0480.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0483.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0486.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0488.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0490.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0492.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0495.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0498.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0499.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0502.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0504.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0506.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0507.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0509.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0512.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0513.jpg", alt: "Jyväskylän yliopisto", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0516.jpg", alt: "Alvar Aalto museo", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0519.jpg", alt: "Alvar Aalto museo", info: "Finlande - Alvar Aalto" },
    
];
