// src/lib/photos.ts
export type Photo = { src: string; alt?: string; info?: string };

export const PHOTOS: Photo[] = [
  { src: "/photos/IP2A0094.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0197.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0097.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0218.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0099.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0222.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0101.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0102.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0104.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0105.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0106.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0107.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0096.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0201.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0214.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0216.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0098.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0100.jpg", alt: "Temppeliaukionkirkko", info: "Finlande - Timo & Tuomo Suomalainen" },
  { src: "/photos/IP2A0224.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0227.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0229.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0233.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0234.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0235.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0237.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0238.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0243.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0244.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0248.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0250.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0251.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0259.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0266.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0271.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0272.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0274.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0276.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0278.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0280.jpg", alt: "Futuro House", info: "Finlande - Matto Suuronen" },
  { src: "/photos/IP2A0297.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0301.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0303.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0304.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0306.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0307.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0314.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0315.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0316.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0318.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0319.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0321.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0322.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
  { src: "/photos/IP2A0324.jpg", alt: "Aalto House", info: "Finlande - Alvar Aalto" },
];
